= Solar Power Systems

A Modelica-library that enables the design and investigation of solar power systems, focusing on the DC power generated by arbitrarily oriented PV modules based on the irradiance in the horizontal plane; air temperature; and wind speed at the site.

WARNING: This is a pre-release version of the library that is not yet intended for public use -- but we're almost there. See the roadmap below for what we're still working on.

== Roadmap

* [x] Ensure that all models perform as intended.
* [x] Remove non-redistributable data from repository and its history.
* [ ] Ensure that scope, dependencies and licenses are clearly indicated in README
* [ ] Add user's guide to library.
* [ ] Point out differences and commonalities with other related libraries.
* [ ] ...
* [ ] Public release of version 1.0.0 according to the https://semver.org/[semver-specification].

== Dependencies
The library depends on several other Modelica-libraries as well as the reference-implementation of the solar position algorithm. The exact versions of the Modelica libraries are specified in the `uses`-annotation in the top-level `package.mo`.

**The following dependencies MUST to be resolved by the user before the models in the library can be used:**

* https://github.com/lbl-srg/modelica-buildings[Modelica `Buildings` library] -- for estimation of diffuse irradiance on the tilted plane; and
* the reference implementation of NREL's Solar Position Algorithm (SPA) available at https://midcdmz.nrel.gov/spa/[https://midcdmz.nrel.gov/spa/].

The implementation of the SPA consists of two files, `spa.h` and `spa.c`, which MUST be put in the directory `./SolarPowerSystems/Resources/Include/`.
